version: '3.8'

services:
  web:
    build: .
    container_name: car_rental_app
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    restart: unless-stopped
    command: python app.py
